// Generated by CoffeeScript 1.6.3
/*
@author Louis Stowasser <louisstow@gmail.com>
License: MIT
*/

(function(exports) {
  var DomBuilder;
  DomBuilder = window["dom_builder"].DomBuilder;
  return exports.generateTOC = function(rootNode, startLevel) {
    var dom, hashable, i, lastLevel, level, lvl, name, node, _i, _len, _ref;
    lastLevel = 0;
    startLevel = startLevel || 2;
    dom = new DomBuilder;
    dom.tag("ul");
    dom.tag("li");
    _ref = rootNode.childNodes;
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      node = _ref[i];
      if (!node.tagName || !/H[0-9]/.test(node.tagName)) {
        continue;
      }
      level = parseInt(node.tagName.substr(1), 10);
      if (level < startLevel) {
        continue;
      }
      name = node.textContent;
      if (!name) {
        continue;
      }
      hashable = name.replace(/[\.\s]/g, "-");
      node.id = hashable;
      if (level === lastLevel) {
        dom.end();
        dom.tag("li");
      } else if (level < lastLevel) {
        lvl = level;
        while (lvl < lastLevel) {
          dom.end().end();
          lvl += 1;
        }
        dom.end().tag("li");
      } else if (level > lastLevel) {
        lvl = level;
        while (lvl < lastLevel) {
          dom.tag("ul").tag("li");
          lvl -= 1;
        }
      }
      dom.tag("a").CLASS('lvl' + level).a("href", "#" + hashable).text(name).end();
      lastLevel = level;
    }
    dom.end();
    return dom.finalize();
  };
})(this["toc_builder"] = {});

/*
//@ sourceMappingURL=toc.map
*/
