// Generated by CoffeeScript 1.6.3
(function(exports) {
  var DomBuilder;
  return exports.DomBuilder = DomBuilder = (function() {
    function DomBuilder(tag) {
      var root;
      if (tag == null) {
        tag = null;
      }
      this.root = root = tag === null ? document.createDocumentFragment() : document.createElement(tag);
      this.current = this.root;
      this.vars = {};
    }

    DomBuilder.prototype.tag = function(name) {
      var e;
      this.current.appendChild(e = document.createElement(name));
      this.current = e;
      return this;
    };

    DomBuilder.prototype.store = function(varname) {
      this.vars[varname] = this.current;
      return this;
    };

    DomBuilder.prototype.rtag = function(var_name, name) {
      this.tag(name);
      return this.store(var_name);
    };

    DomBuilder.prototype.end = function() {
      var cur;
      this.current = cur = this.current.parentNode;
      if (cur === null) {
        throw new Error("Too many end()'s");
      }
      return this;
    };

    DomBuilder.prototype.text = function(txt) {
      this.current.appendChild(document.createTextNode(txt));
      return this;
    };

    DomBuilder.prototype.a = function(name, value) {
      this.current.setAttribute(name, value);
      return this;
    };

    DomBuilder.prototype.append = function(elementReference) {
      this.current.appendChild(elementReference);
      return this;
    };

    DomBuilder.prototype.DIV = function() {
      return this.tag("div");
    };

    DomBuilder.prototype.A = function() {
      return this.tag("a");
    };

    DomBuilder.prototype.SPAN = function() {
      return this.tag("span");
    };

    DomBuilder.prototype.ID = function(id) {
      return this.a("id", id);
    };

    DomBuilder.prototype.CLASS = function(cls) {
      return this.a("class", cls);
    };

    DomBuilder.prototype.finalize = function() {
      var r;
      r = this.root;
      this.root = this.current = this.vars = null;
      return r;
    };

    return DomBuilder;

  })();
})(this["dom_builder"] = {});

/*
//@ sourceMappingURL=dom-builder.map
*/
