// Generated by CoffeeScript 1.6.3
"use strict";
/*
Exact palette quantizer. Returns palette as array of bytes
*/

var exactPalette;

exactPalette = function(rgbaImage, indexImage) {
  var b, g, i, idx, j, pal, r, rgb, rgb2index, _i, _ref;
  pal = [];
  rgb2index = {};
  j = 0;
  for (i = _i = 0, _ref = rgbaImage.length; _i < _ref; i = _i += 4) {
    r = rgbaImage[i];
    g = rgbaImage[i + 1];
    b = rgbaImage[i + 2];
    rgb = r | (g << 8) | (b << 16);
    idx = rgb2index[rgb];
    if (idx === undefined) {
      if (pal.length < 256 * 3) {
        idx = (pal.length / 3) | 0;
        rgb2index[rgb] = idx;
        pal.push(r);
        pal.push(g);
        pal.push(b);
      } else {
        idx = 0;
      }
    }
    indexImage[j] = idx;
    ++j;
  }
  return pal;
};

/*
//@ sourceMappingURL=ExactPaletteQuant.map
*/
